# Generated by Django 4.1.5 on 2023-02-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0003_breed_rabbitstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buck_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Doe_name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rabbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('H', 'Hembra'), ('M', 'Macho')], default='M', max_length=1)),
                ('rabbit_tag', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('rabbit_photo', models.ImageField(blank=True, null=True, upload_to='media/rabbits', verbose_name='Foto del conejo')),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.breed')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rabbit.buck')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rabbit.doe')),
                ('rabbit_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.rabbitstatus')),
            ],
            options={
                'verbose_name': 'Rabbit',
                'verbose_name_plural': 'Rabbits',
            },
        ),
    ]
