# Generated by Django 4.1.5 on 2023-02-27 21:34

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cage', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rabbit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], default='Macho', max_length=1)),
                ('rabbit_tag', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('weight', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('rabbit_photo', models.ImageField(blank=True, null=True, upload_to='media/rabbits', verbose_name='Foto del conejo')),
                ('observation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default='Si')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.breed')),
                ('cage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cage.cage')),
                ('rabbit_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.rabbitstatus')),
            ],
            options={
                'verbose_name': 'Rabbit',
                'verbose_name_plural': 'Rabbits',
            },
            managers=[
                ('record_set', django.db.models.manager.Manager()),
            ],
        ),
    ]
