# Generated by Django 4.1.5 on 2023-02-27 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabbit', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rabbit',
            options={'default_manager_name': 'objects', 'verbose_name': 'Rabbit', 'verbose_name_plural': 'Rabbits'},
        ),
        migrations.AlterModelManagers(
            name='rabbit',
            managers=[
            ],
        ),
    ]
