# Generated by Django 4.1.5 on 2023-03-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbit', '0003_alter_rabbit_rabbit_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbit',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
