# Generated by Django 4.1.5 on 2023-03-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbit', '0004_alter_rabbit_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbit',
            name='rabbit_photo',
            field=models.ImageField(blank=True, default='rabbit_avatar.png', null=True, upload_to='media/rabbits', verbose_name='Foto del conejo'),
        ),
    ]
