# Generated by Django 4.1.5 on 2023-03-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbit', '0005_alter_rabbit_rabbit_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabbit',
            name='rabbit_photo',
            field=models.ImageField(blank=True, default='rabbit_avatar.png', null=True, upload_to='media/rabbits/', verbose_name='Foto del conejo'),
        ),
    ]
