# Generated by Django 4.1.5 on 2023-03-07 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rabbit', '0006_alter_rabbit_rabbit_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rabbit',
            name='observation',
        ),
    ]
