# Generated by Django 4.1.5 on 2023-03-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rabbit', '0007_remove_rabbit_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabbit',
            name='is_buck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rabbit',
            name='is_doe',
            field=models.BooleanField(default=False),
        ),
    ]
