# Generated by Django 4.1.5 on 2024-08-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('activity', models.TextField(max_length=255)),
                ('transaction_type', models.CharField(choices=[('G', 'Gasto'), ('I', 'Ingreso')], default='Gasto', max_length=1)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10, null=True)),
                ('reference', models.CharField(blank=True, default='S/R', max_length=20, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'activity',
                'verbose_name_plural': 'activities',
                'ordering': ('-activity_date',),
            },
        ),
    ]
