# Generated by Django 4.1.5 on 2023-03-12 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rabbit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doe_name', models.CharField(max_length=30)),
                ('selection_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doe_rabbit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rabbit.rabbit')),
            ],
            options={
                'verbose_name': 'Doe',
                'verbose_name_plural': 'Does',
                'default_manager_name': 'objects',
            },
        ),
    ]
