# Generated by Django 4.1.5 on 2023-03-07 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doe', '0002_doe_rabbit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doe',
            old_name='rabbit',
            new_name='doe_rabbit',
        ),
        migrations.AddField(
            model_name='doe',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
