# Generated by Django 4.1.5 on 2023-03-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doe', '0003_remove_doe_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doe',
            name='doe_name',
            field=models.CharField(max_length=50),
        ),
    ]
