# Generated by Django 4.1.5 on 2023-03-09 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doe', '0003_rename_rabbit_doe_doe_rabbit_doe_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doe',
            options={'default_manager_name': 'objects', 'verbose_name': 'Doe', 'verbose_name_plural': 'Does'},
        ),
    ]
