# Generated by Django 4.1.7 on 2023-04-05 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buck_name', models.CharField(max_length=50)),
                ('selection_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Buck',
                'verbose_name_plural': 'Bucks',
                'default_manager_name': 'objects',
            },
        ),
    ]
