# Generated by Django 4.1.5 on 2023-03-16 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rabbit', '0001_initial'),
        ('buck', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buck',
            options={'default_manager_name': 'objects', 'verbose_name': 'Buck', 'verbose_name_plural': 'Bucks'},
        ),
        migrations.AddField(
            model_name='buck',
            name='buck_rabbit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rabbit.rabbit'),
        ),
        migrations.AddField(
            model_name='buck',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='buck',
            name='buck_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='buck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
