# Generated by Django 4.1.5 on 2024-08-02 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rabbit', '0001_initial'),
        ('farms', '0001_initial'),
        ('buck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buck',
            name='buck_rabbit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rabbit.rabbit'),
        ),
        migrations.AddField(
            model_name='buck',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.producerprofile'),
        ),
    ]
