# Generated by Django 4.1.7 on 2023-03-23 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rabbit', '0001_initial'),
        ('buck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buck',
            name='buck_rabbit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rabbit.rabbit'),
        ),
    ]
