# Generated by Django 4.1.5 on 2023-02-10 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
