# Generated by Django 4.1.5 on 2023-02-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_user', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
