# Generated by Django 4.1.5 on 2024-08-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cage_title', models.CharField(max_length=50, unique=True)),
                ('is_public', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('cage_photo', models.ImageField(blank=True, default='cage_avatar.png', null=True, upload_to='media/cage', verbose_name='Producer profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lista de Jaulas',
                'verbose_name_plural': 'Total de Jaulas',
                'default_manager_name': 'objects',
            },
        ),
    ]
