# Generated by Django 4.1.5 on 2023-02-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cage_title', models.CharField(max_length=50, unique=True)),
                ('batch_number', models.PositiveIntegerField(blank=True, null=True)),
                ('rabbits_number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_public', models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=False)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('cage_photo', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Producer profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
