# Generated by Django 4.1.5 on 2023-02-16 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cage', '0001_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cage',
            name='farm_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.producerprofile'),
        ),
    ]
