# Generated by Django 4.1.5 on 2023-02-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cage', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cage',
            old_name='farm_id',
            new_name='farm',
        ),
    ]
