# Generated by Django 4.1.5 on 2023-03-02 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_initial'),
        ('cage', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cage',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cages', to='farms.producerprofile'),
        ),
    ]
