# Generated by Django 4.1.5 on 2023-03-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cage', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cage',
            name='cage_photo',
            field=models.ImageField(blank=True, default='cage_avatar.png', null=True, upload_to='media/cage', verbose_name='Producer profile'),
        ),
    ]
