# Generated by Django 4.1.5 on 2023-03-04 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cage', '0003_alter_cage_farm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cage',
            options={'default_manager_name': 'objects', 'verbose_name': 'Lista de Jaulas', 'verbose_name_plural': 'Total de Jaulas'},
        ),
        migrations.AlterField(
            model_name='cage',
            name='rabbits_number',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
