# Generated by Django 4.1.5 on 2023-02-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cage', '0004_alter_cage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cage',
            name='is_producer',
            field=models.BooleanField(default=False),
        ),
    ]
