# Generated by Django 4.1.5 on 2023-03-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cage', '0004_alter_cage_options_alter_cage_rabbits_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
