# Generated by Django 4.1.5 on 2023-02-20 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cage', '0005_cage_is_producer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cage',
            name='is_producer',
        ),
    ]
