# Generated by Django 4.1.5 on 2023-02-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerprofile',
            name='is_producer',
            field=models.BooleanField(default=False),
        ),
    ]
