# Generated by Django 4.1.5 on 2023-02-14 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_city_city_alter_city_state_id'),
        ('farms', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producerprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='city',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.city'),
        ),
        migrations.AlterField(
            model_name='producerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Producer profile'),
        ),
    ]
