# Generated by Django 4.1.5 on 2023-02-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_producerprofile_is_producer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producerprofile',
            name='is_producer',
        ),
    ]
