# Generated by Django 4.1.5 on 2023-02-14 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_city_city_alter_city_state_id'),
        ('farms', '0003_remove_producerprofile_state_producerprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.city'),
        ),
    ]
