# Generated by Django 4.1.5 on 2023-02-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_remove_producerprofile_is_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='producerprofile',
            name='is_producer',
            field=models.BooleanField(default=False),
        ),
    ]
