# Generated by Django 4.1.5 on 2023-02-15 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_alter_producerprofile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producerprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
