# Generated by Django 4.1.7 on 2023-04-05 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doe', '0001_initial'),
        ('buck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, default='')),
                ('mating_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buck.buck')),
                ('doe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doe.doe')),
            ],
        ),
    ]
