# Generated by Django 4.1.7 on 2023-03-23 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doe', '0001_initial'),
        ('buck', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, default='')),
                ('vote', models.IntegerField(choices=[(0, 'NINGUNA'), (1, 'UNA'), (2, 'DOS'), (3, 'TRES'), (4, 'CUATRO'), (5, 'CINCO')], default=0, verbose_name='stars')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buck.buck')),
                ('doe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doe.doe')),
            ],
        ),
    ]
