# Generated by Django 4.1.7 on 2023-04-09 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('buck', '0001_initial'),
        ('doe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mating_date', models.DateField(blank=True, null=True)),
                ('observations', models.TextField(max_length=255)),
                ('mating_succeeded', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buck.buck')),
                ('doe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doe.doe')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farms.producerprofile')),
            ],
            options={
                'verbose_name': 'Mating',
                'verbose_name_plural': 'Matings',
            },
        ),
    ]
